### ISSUE TITLE
Missing/incorrect info: Missing class recording for Tuesday 1/17/23 and Thursday 1/19/23

### ISSUE THREAD

**Issue by kpwhit** [comp426-2023-spring/syllabus#7]
#### URL of file with the missing/incorrect info
Panopto: https://uncch.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx#folderID=%2219872ac0-1b5a-4093-af2a-af88015ddb9b%22

Schedule page: https://github.com/comp426-2023-spring/schedule/

#### Line number with missing or incorrect info
N/A

#### What is wrong?
Panopto: Missing recording files for class on Tuesday 1/17/23 and Thursday 1/19/23.
Schedule page: Missing links to recordings for class on Tuesday 1/17/23 and Thursday 1/19/23 on respective days.

#### What should be there instead?
Panopto: Recording files for class on Tuesday 1/17/23 and Thursday 1/19/23.
Schedule page: Links to recordings for class on Tuesday 1/17/23 and Thursday 1/19/23 on respective days.

**Comment by jdmar3** [comment]
Fixed in https://github.com/comp426-2023-spring/schedule/commit/0ad9ec9ea8c31fbc231e8e6056932c573333c815
